# Generated by Django 5.0.6 on 2024-06-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_video_coordinates_video_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='knee_flexion_left',
        ),
        migrations.RemoveField(
            model_name='video',
            name='knee_flexion_right',
        ),
    ]
