# Generated by Django 5.0.6 on 2024-06-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_video_knee_flexion_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cadence_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='video',
            name='cadence_right',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='video',
            name='speed_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='video',
            name='speed_right',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
