# Generated by Django 5.0.6 on 2024-06-07 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_video_cadence_left_alter_video_cadence_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
