program: train.py
method: bayes
metric:
  goal: minimize
  name: best_validation_loss
parameters:
  dropout_amount:
    min: 0.0
    max: 0.5
  last_layer_dim:
    min: 10
    max: 128
  learning_rate:
    min: 0.0001
    max: 0.05
  nr_epochs:
    value: 30
  model_architecture:
    value: CNN